#!/bin/bash
echo "Updating meshblu-osc"
./core-auto-update meshblu-osc
echo "Updating meshblu-myo"
./core-auto-update meshblu-myo
echo "Updating meshblu-lifx-light"
./core-auto-update meshblu-lifx-light
echo "Updating meshblu-hue"
./core-auto-update meshblu-hue
echo "Updating meshblu-hue-button"
./core-auto-update meshblu-hue-button
echo "Updating meshblu-hue-light"
./core-auto-update meshblu-hue-light
echo "Updating meshblu-drone-army"
./core-auto-update meshblu-drone-army
echo "Updating meshblu-alljoyn"
./core-auto-update meshblu-alljoyn
echo "Updating meshblu-aim"
./core-auto-update meshblu-aim
echo "Updating meshblu-serial"
./core-auto-update meshblu-serial
echo "Updating meshblu-http-connector"
./core-auto-update meshblu-http-connector
echo "Updating meshblu-beacon"
./core-auto-update meshblu-beacon
echo "Updating meshblu-mindwave"
./core-auto-update meshblu-mindwave
echo "Updating meshblu-citrix-receiver"
./core-auto-update meshblu-citrix-receiver
echo "Updating meshblu-discovery-master"
./core-auto-update meshblu-discovery-master
echo "Updating meshblu-lifx"
./core-auto-update meshblu-lifx
echo "Updating meshblu-device-discoverer"
./core-auto-update meshblu-device-discoverer
echo "Updating meshblu-chromecast"
./core-auto-update meshblu-chromecast
echo "Updating meshblu-blink1"
./core-auto-update meshblu-blink1
echo "Updating meshblu-arduino"
./core-auto-update meshblu-arduino
echo "Updating meshblu-tentacle"
./core-auto-update meshblu-tentacle
echo "Updating meshblu-bean"
./core-auto-update meshblu-bean
echo "Updating meshblu-insteon"
./core-auto-update meshblu-insteon
echo "Updating meshblu-ble-heartrate"
./core-auto-update meshblu-ble-heartrate
echo "Updating meshblu-shell"
./core-auto-update meshblu-shell
echo "Updating meshblu-sonos"
./core-auto-update meshblu-sonos
echo "Updating meshblu-blendmicro"
./core-auto-update meshblu-blendmicro
echo "Updating meshblu-mac-vhid"
./core-auto-update meshblu-mac-vhid
echo "Updating meshblu-wemo"
./core-auto-update meshblu-wemo
echo "Updating meshblu-greeting"
./core-auto-update meshblu-greeting
echo "Updating meshblu-blinky-tape"
./core-auto-update meshblu-blinky-tape
echo "Updating meshblu-lumencache"
./core-auto-update meshblu-lumencache
echo "Updating meshblu-cam"
./core-auto-update meshblu-cam
echo "Updating meshblu-twitter-stream"
./core-auto-update meshblu-twitter-stream
echo "Updating meshblu-relayr"
./core-auto-update meshblu-relayr
echo "Updating meshblu-giphy"
./core-auto-update meshblu-giphy
echo "Updating meshblu-git-run"
./core-auto-update meshblu-git-run
echo "Updating meshblu-oculus"
./core-auto-update meshblu-oculus
echo "Updating meshblu-sensoria"
./core-auto-update meshblu-sensoria
echo "Updating meshblu-meshlium"
./core-auto-update meshblu-meshlium
echo "Updating meshblu-gotomeeting-osa"
./core-auto-update meshblu-gotomeeting-osa
echo "Updating meshblu-echo"
./core-auto-update meshblu-echo
echo "Updating meshblu-xbee"
./core-auto-update meshblu-xbee
echo "Updating meshblu-banjocanyon"
./core-auto-update meshblu-banjocanyon
