#!/bin/bash

usage() {
  echo "./core-auto-update <connector-name>"
  echo "   Connector name should not include 'meshblu-connector-' or 'meshblu-'"
  echo "Required Enviroment"
  echo "   env NPM_SECRET_KEY"
  echo "   env GITHUB_RELEASE_KEY"
  echo "   env APPVEYOR_GITHUB_RELEASE_KEY"
}

main() {
  local connector="$1"
  local npm_secret_key="$NPM_SECRET_KEY"
  local github_release_key="$GITHUB_RELEASE_KEY"
  local appveyor_github_key="$APPVEYOR_GITHUB_RELEASE_KEY"

  if [ -z "$connector" ]; then
    usage
    echo "Missing connector-name"
    exit 1
  fi

  if [ -z "$npm_secret_key" ]; then
    usage
    echo "Missing env NPM_SECRET_KEY"
  fi

  if [ -z "$github_release_key" ]; then
    usage
    echo "Missing env GITHUB_RELEASE_KEY"
  fi

  if [ -z "$appveyor_github_key" ]; then
    usage
    echo "Missing env APPVEYOR_GITHUB_RELEASE_KEY"
  fi
}

main "$@"
