#!/bin/bash
echo "Updating meshblu-osc"
./update-connector meshblu-osc
echo "Updating meshblu-myo"
./update-connector meshblu-myo
echo "Updating meshblu-lifx-light"
./update-connector meshblu-lifx-light
echo "Updating meshblu-hue"
./update-connector meshblu-hue
echo "Updating meshblu-hue-button"
./update-connector meshblu-hue-button
echo "Updating meshblu-hue-light"
./update-connector meshblu-hue-light
echo "Updating meshblu-drone-army"
./update-connector meshblu-drone-army
echo "Updating meshblu-alljoyn"
./update-connector meshblu-alljoyn
echo "Updating meshblu-aim"
./update-connector meshblu-aim
echo "Updating meshblu-serial"
./update-connector meshblu-serial
echo "Updating meshblu-http-connector"
./update-connector meshblu-http-connector
echo "Updating meshblu-beacon"
./update-connector meshblu-beacon
echo "Updating meshblu-mindwave"
./update-connector meshblu-mindwave
echo "Updating meshblu-citrix-receiver"
./update-connector meshblu-citrix-receiver
echo "Updating meshblu-discovery-master"
./update-connector meshblu-discovery-master
echo "Updating meshblu-lifx"
./update-connector meshblu-lifx
echo "Updating meshblu-device-discoverer"
./update-connector meshblu-device-discoverer
echo "Updating meshblu-chromecast"
./update-connector meshblu-chromecast
echo "Updating meshblu-blink1"
./update-connector meshblu-blink1
echo "Updating meshblu-arduino"
./update-connector meshblu-arduino
echo "Updating meshblu-tentacle"
./update-connector meshblu-tentacle
echo "Updating meshblu-bean"
./update-connector meshblu-bean
echo "Updating meshblu-insteon"
./update-connector meshblu-insteon
echo "Updating meshblu-ble-heartrate"
./update-connector meshblu-ble-heartrate
echo "Updating meshblu-shell"
./update-connector meshblu-shell
echo "Updating meshblu-sonos"
./update-connector meshblu-sonos
echo "Updating meshblu-blendmicro"
./update-connector meshblu-blendmicro
echo "Updating meshblu-mac-vhid"
./update-connector meshblu-mac-vhid
echo "Updating meshblu-wemo"
./update-connector meshblu-wemo
echo "Updating meshblu-greeting"
./update-connector meshblu-greeting
echo "Updating meshblu-blinky-tape"
./update-connector meshblu-blinky-tape
echo "Updating meshblu-lumencache"
./update-connector meshblu-lumencache
echo "Updating meshblu-cam"
./update-connector meshblu-cam
echo "Updating meshblu-twitter-stream"
./update-connector meshblu-twitter-stream
echo "Updating meshblu-relayr"
./update-connector meshblu-relayr
echo "Updating meshblu-giphy"
./update-connector meshblu-giphy
echo "Updating meshblu-git-run"
./update-connector meshblu-git-run
echo "Updating meshblu-oculus"
./update-connector meshblu-oculus
echo "Updating meshblu-sensoria"
./update-connector meshblu-sensoria
echo "Updating meshblu-meshlium"
./update-connector meshblu-meshlium
echo "Updating meshblu-gotomeeting-osa"
./update-connector meshblu-gotomeeting-osa
echo "Updating meshblu-echo"
./update-connector meshblu-echo
echo "Updating meshblu-xbee"
./update-connector meshblu-xbee
echo "Updating meshblu-banjocanyon"
./update-connector meshblu-banjocanyon
